# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://172.26.180.229:3306/zz_test?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&&serverTimezone=${app.defaultTimeZone:Asia/Shanghai}
    username: root
    password: password@Mysql
    driver-class-name: com.mysql.cj.jdbc.Driver