spring:
  profiles:
    active: dev
  application:
    name: feign-client

server:
  port: 7001
  servlet:
    context-path: /feign-client

#health：http://localhost:7001/feign-client/actuator/health
#info：http://localhost:7001/feign-client/actuator/info    
management:
  endpoints:
    web:
      exposure:
        include: '*'
       
logging:
  level:
    root: INFO  # 设置所有目录的日志级别      
    com.zz.test.server.feign: DEBUG
feign: #FeignClientFactoryBean中的loadBalance方法断点看用哪个
  httpclient:
    enabled: false
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数    
  okhttp:
    enabled: true     
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数    