spring:
  profiles:
    active: dev
  application:
    name: feign-client

server:
  port: 7001
  servlet:
    context-path: /feign-client

#health：http://localhost:7001/feign-client/actuator/health
#info：http://localhost:7001/feign-client/actuator/info    
management:
  endpoints:
    web:
      exposure:
        include: '*'
       
logging:
  level:
    root: INFO  # 设置所有目录的日志级别      
    com.zz.test.server.feign: DEBUG
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true     