spring:
  profiles:
    active: dev
  application:
    name: feign-client

server:
  port: 7001
  servlet:
    context-path: /feign-client

#health：http://localhost:7001/feign-client/actuator/health
#info：http://localhost:7001/feign-client/actuator/info    
management:
  endpoints:
    web:
      exposure:
        include: '*'
       
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: full
      timeout10s:
        connectTimeout: 2000
        readTimeout: 10000
        loggerLevel: full
  httpclient:
    enabled: false
  okhttp:
    enabled: true     