spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: Ruijie@Redis
    database: 3 #操作的是0号数据库
    jedis:
      #Redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: -1 #连接池最大阻塞等待时间 默认值-1  负数表示无限制
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接